# Generated by Django 3.2 on 2021-04-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210425_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
