# Generated by Django 3.2 on 2021-04-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_newusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newusermodel',
            old_name='address',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='newusermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='newusermodel',
            name='state',
        ),
    ]
