# Generated by Django 3.2 on 2021-04-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210428_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusermodel',
            name='username',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
