# Generated by Django 3.2 on 2021-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
