# Generated by Django 3.2 on 2021-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_theproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theproduct',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
